apiVersion: batch/v1
kind: Job
metadata:
  name: delete-evicted-pod
  labels:
    app: delete-evicted-pod
spec:
  template:
    metadata:
      name: delete-evicted-pod
      labels:
        app: delete-evicted-pod
    spec:
      serviceAccountName: sre
      containers:
      - name: delete-evicted-pod
        image: asia.gcr.io/pl-web-219210/delete-evicted-pod:latest
      restartPolicy: Never
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: gcr-json-key