apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: delete-evicted-pod
build:
  artifacts:
  - image: delete-evicted-pod
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
    - kustomize