apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: delete-evicted-pod
build:
  artifacts:
  - image: asia.gcr.io/pl-web-219210/delete-evicted-pod
    kaniko: {}
  googleCloudBuild:
    projectId: pl-web-219210
deploy:
  kustomize:
    paths:
    - kustomize